openssl-cmake: move the test from Dockerfile to CMakeLists.txt
The heredoc <<C_CODE did not work properly and because of that the build
failed with the following:

    Feb 18 17:02:03 [ 99%] Built target bssl
    Feb 18 17:02:03 [100%] Building C object util/fipstools/CMakeFiles/test_fips.dir/test_fips.c.o
    Feb 18 17:02:03 [100%] Linking C executable test_fips
    Feb 18 17:02:03 [100%] Built target test_fips
    Feb 18 17:02:08  ---> Removed intermediate container ca5081cc5009
    Feb 18 17:02:08  ---> d167b35a094a
    Feb 18 17:02:08 Step 6/9 : RUN cd /aws-lc-AWS-LC-FIPS-2.0.0/build     && <<C_CODE gcc -x c - -o ./check_version -L./ssl -l:libssl.a -L./crypto -l:libcrypto.a && ./check_version 'AWS-LC FIPS 2.0.0'
    Feb 18 17:02:08  ---> Running in 11db7bffe142
    Feb 18 17:02:08 /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
    Feb 18 17:02:08 (.text+0x1b): undefined reference to `main'
    Feb 18 17:02:08 collect2: error: ld returned 1 exit status
    Feb 18 17:02:08 The command '/bin/sh -c cd /aws-lc-AWS-LC-FIPS-2.0.0/build     && <<C_CODE gcc -x c - -o ./check_version -L./ssl -l:libssl.a -L./crypto -l:libcrypto.a && ./check_version 'AWS-LC FIPS 2.0.0'' returned a non-zero code: 1

This commit moves the tester to CMakeLists.txt and therefore fixes the
problem